### Chupa hu function

##### np.sort
###### return a sorted copy of array

In [81]:
# code 
import numpy as np

# wecan use "sorting" => problem in output it gives "list"

a = np.random.randint(1,100,15)
a


array([32, 62, 24,  2, 70, 56, 24, 89, 56, 94, 63, 39, 20, 76, 66])

In [82]:
b = np.random.randint(1,100, 24).reshape(6,4)

b

array([[96, 61, 61, 38],
       [93, 92, 63, 98],
       [57, 73, 36, 63],
       [ 1, 37, 51, 12],
       [84, 90, 93, 69],
       [51, 36, 27, 68]])

In [83]:
np.sort(a)


array([ 2, 20, 24, 24, 32, 39, 56, 56, 62, 63, 66, 70, 76, 89, 94])

In [84]:
np.sort(a)[::-1]
# reverse order written in this way as , it does not have reverse = True

array([94, 89, 76, 70, 66, 63, 62, 56, 56, 39, 32, 24, 24, 20,  2])

In [85]:
np.sort(b)
# row wise sorting

array([[38, 61, 61, 96],
       [63, 92, 93, 98],
       [36, 57, 63, 73],
       [ 1, 12, 37, 51],
       [69, 84, 90, 93],
       [27, 36, 51, 68]])

In [86]:
np.sort(b, axis = 0)
# column wise sorting

array([[ 1, 36, 27, 12],
       [51, 37, 36, 38],
       [57, 61, 51, 63],
       [84, 73, 61, 68],
       [93, 90, 63, 69],
       [96, 92, 93, 98]])

##### np.append
###### append the item at the end of the given axis


In [87]:
np.append(a,200)

array([ 32,  62,  24,   2,  70,  56,  24,  89,  56,  94,  63,  39,  20,
        76,  66, 200])

In [88]:
# apppend a column with all 1

np.append(b,np.ones((b.shape[0],1)), axis = 1)


# insert random
np.append(b,np.random.random((b.shape[0],1)), axis = 1)


array([[9.60000000e+01, 6.10000000e+01, 6.10000000e+01, 3.80000000e+01,
        6.55404223e-02],
       [9.30000000e+01, 9.20000000e+01, 6.30000000e+01, 9.80000000e+01,
        9.43981809e-01],
       [5.70000000e+01, 7.30000000e+01, 3.60000000e+01, 6.30000000e+01,
        7.07207832e-01],
       [1.00000000e+00, 3.70000000e+01, 5.10000000e+01, 1.20000000e+01,
        5.62499888e-01],
       [8.40000000e+01, 9.00000000e+01, 9.30000000e+01, 6.90000000e+01,
        7.52142926e-01],
       [5.10000000e+01, 3.60000000e+01, 2.70000000e+01, 6.80000000e+01,
        9.77057158e-01]])

##### np.concatenate
###### function concatenate a sequence of arrays along an existing axis

In [89]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)

print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [90]:
np.concatenate((c,d), axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

##### np.unique
###### unique values a array passed

In [91]:
e = np.array([1,2,3,3,4,4,44,4,3,2,2,3,4,5,5,6,66,7,7,7,8,8,8,9,9])

In [92]:
np.unique(e)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 44, 66])

##### np.expand_dims
###### we can ged the expanded dimensions of array

In [93]:
a
a.shape

(15,)

In [94]:
np.expand_dims(a,axis = 0)

array([[32, 62, 24,  2, 70, 56, 24, 89, 56, 94, 63, 39, 20, 76, 66]])

In [95]:
np.expand_dims(a,axis = 0).shape

(1, 15)

In [96]:
np.expand_dims(a,axis = 1)

array([[32],
       [62],
       [24],
       [ 2],
       [70],
       [56],
       [24],
       [89],
       [56],
       [94],
       [63],
       [39],
       [20],
       [76],
       [66]])

In [97]:
np.expand_dims(a,axis = 1).shape

(15, 1)

##### machine learning => prediction

##### np.where
###### function return the indicies of element in an input array where where the given condition is satisfied

In [98]:
a

array([32, 62, 24,  2, 70, 56, 24, 89, 56, 94, 63, 39, 20, 76, 66])

In [99]:
# tell me index whose value > 50

np.where(a>50)

(array([ 1,  4,  5,  7,  8,  9, 10, 13, 14], dtype=int64),)

In [100]:
# repalce all valuses greater than 50 replace by "🔴" imp🌟

# np.where(condition , true , false)

np.where(a>50 ,"🔴",a)

array(['32', '🔴', '24', '2', '🔴', '🔴', '24', '🔴', '🔴', '🔴', '🔴', '39',
       '20', '🔴', '🔴'], dtype='<U11')

In [101]:
# repalce even number 

np.where(a % 2 == 0 , 0 , a)

array([ 0,  0,  0,  0,  0,  0,  0, 89,  0,  0, 63, 39,  0,  0,  0])

##### np.argmax 🌟
###### max element index of given axis


In [102]:
a

array([32, 62, 24,  2, 70, 56, 24, 89, 56, 94, 63, 39, 20, 76, 66])

In [103]:
np.argmax(a)
# used in 1d mostly

9

In [104]:
# 2D
# axis = 0 , column 
b

array([[96, 61, 61, 38],
       [93, 92, 63, 98],
       [57, 73, 36, 63],
       [ 1, 37, 51, 12],
       [84, 90, 93, 69],
       [51, 36, 27, 68]])

In [105]:
np.argmax(b, axis= 0)

array([0, 1, 4, 1], dtype=int64)

##### np.argmin
###### min element index of given axis


In [106]:
np.argmin(a)

3

##### np.cumsum 
###### cumulative sum over a given axis

In [107]:
a

array([32, 62, 24,  2, 70, 56, 24, 89, 56, 94, 63, 39, 20, 76, 66])

In [108]:
np.cumsum(a)
# total sum of all previous and current

array([ 32,  94, 118, 120, 190, 246, 270, 359, 415, 509, 572, 611, 631,
       707, 773])

In [109]:
b

array([[96, 61, 61, 38],
       [93, 92, 63, 98],
       [57, 73, 36, 63],
       [ 1, 37, 51, 12],
       [84, 90, 93, 69],
       [51, 36, 27, 68]])

In [110]:
np.cumsum(b, axis = 0)
# 0 => column

array([[ 96,  61,  61,  38],
       [189, 153, 124, 136],
       [246, 226, 160, 199],
       [247, 263, 211, 211],
       [331, 353, 304, 280],
       [382, 389, 331, 348]])

##### np.cumprod

In [111]:
np.cumprod(a)

array([         32,        1984,       47616,       95232,     6666240,
         373309440,   369491968, -1474953216,  -993001472,  1147142144,
        -744488960,  1029701632,  -880803840,  1778384896,  1409286144])

##### np.percentile
###### compute the nth percentile of the given data along the specified axis

In [112]:
a

array([32, 62, 24,  2, 70, 56, 24, 89, 56, 94, 63, 39, 20, 76, 66])

In [113]:
np.percentile(a,100)

# max in list 

94.0

In [114]:
np.percentile(a,50)


56.0

In [115]:
# same as 50 half
np.median(a)

56.0

In [116]:
np.percentile(a,0)


2.0

In [117]:
# percentile formula p = (n/N)*100   n = number below 'x' , N = total count of population

##### np.histogram
###### frequency counts 

In [118]:
a

array([32, 62, 24,  2, 70, 56, 24, 89, 56, 94, 63, 39, 20, 76, 66])

In [119]:
np.histogram(a, bins = [0, 10, 20 , 30, 40, 50, 60, 70 ,80, 90, 100])

(array([1, 0, 3, 2, 0, 2, 3, 2, 1, 1], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

##### np.corrcoef 🌟
###### eak bhadne se dusare pe kay effect padta hai
######  [-1 , 1]  lies between these , -1 inverse , 0 no relation , 1 direct relation

In [120]:
salary = np.array([10000, 20000, 30000, 40000 , 45000])

experince = np.array([1,2,4,2,6])

np.corrcoef(salary , experince)


#             salary    experince
# salary        1.         0.74
# experince     0.74       1.

# 2 quantity 2x2 , if 3 then 3x3

array([[1.        , 0.74208219],
       [0.74208219, 1.        ]])

##### np.isin
###### in a array search for multiple items , like u search for 2,3,4,5,6 in array is all elements are present

In [121]:
a

array([32, 62, 24,  2, 70, 56, 24, 89, 56, 94, 63, 39, 20, 76, 66])

In [122]:
items  = [10,20,30, 40,50,60,70,80,90,100]

np.isin(a, items)

# jaha pe hai baha pe true , else false

array([False, False, False, False,  True, False, False, False, False,
       False, False, False,  True, False, False])

In [123]:
a[np.isin(a, items)]

array([70, 20])

##### np.flip
###### reverse the order of array elements along the specified axis , prserving the shape of the array

In [124]:
# code 
a

array([32, 62, 24,  2, 70, 56, 24, 89, 56, 94, 63, 39, 20, 76, 66])

In [125]:
np.flip(a)

array([66, 76, 20, 39, 63, 94, 56, 89, 24, 56, 70,  2, 24, 62, 32])

In [126]:
b

array([[96, 61, 61, 38],
       [93, 92, 63, 98],
       [57, 73, 36, 63],
       [ 1, 37, 51, 12],
       [84, 90, 93, 69],
       [51, 36, 27, 68]])

In [130]:
np.flip(b, axis = 0)

array([[51, 36, 27, 68],
       [84, 90, 93, 69],
       [ 1, 37, 51, 12],
       [57, 73, 36, 63],
       [93, 92, 63, 98],
       [96, 61, 61, 38]])

In [132]:
np.flip(b)

array([[68, 27, 36, 51],
       [69, 93, 90, 84],
       [12, 51, 37,  1],
       [63, 36, 73, 57],
       [98, 63, 92, 93],
       [38, 61, 61, 96]])

##### np.put
######  permanent changes , replace the (edit) the valuses as per as index number

In [133]:
a

array([32, 62, 24,  2, 70, 56, 24, 89, 56, 94, 63, 39, 20, 76, 66])

In [134]:
np.put(a,[0,1],[110, 530])

In [135]:
a

array([110, 530,  24,   2,  70,  56,  24,  89,  56,  94,  63,  39,  20,
        76,  66])

##### np.delete
###### delete any specific  number as per as index


In [136]:
np.delete(a,0)

array([530,  24,   2,  70,  56,  24,  89,  56,  94,  63,  39,  20,  76,
        66])

In [137]:
np.delete(a,[0,2,4])

array([530,   2,  56,  24,  89,  56,  94,  63,  39,  20,  76,  66])

##### set functions


In [139]:
# np.union1d

m = np.array([1,2,3,4,5])
n = np.array([4,8,3,7,5])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 7, 8])

In [140]:
# np.intersect1d

m = np.array([1,2,3,4,5])
n = np.array([4,8,3,7,5])

np.intersect1d(m,n)

array([3, 4, 5])

In [142]:
np.setdiff1d(m,n) # m mai hai per n mai nahi

array([1, 2])

In [143]:
# remove common
np.setxor1d(m,n)

array([1, 2, 7, 8])

In [145]:
# in  1 d => bo cheej hai ki nahi
np.in1d(m,1)


array([ True, False, False, False, False])

##### np.clip

In [146]:
a

array([110, 530,  24,   2,  70,  56,  24,  89,  56,  94,  63,  39,  20,
        76,  66])

In [147]:
# keep values in a range

np.clip(a,a_min = 25 , a_max = 75)

array([75, 75, 25, 25, 70, 56, 25, 75, 56, 75, 63, 39, 25, 75, 66])