In [3]:
# part2 
import numpy as np

ARRAY ATTRIBTES

In [7]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [10]:
# ndim => find dimensions

a3.ndim

3

In [14]:
# shape => har dimension mai kitne item hai

a3.shape


(2, 2, 2)

In [16]:
# size =>  number of item

a3.size

8

In [19]:
# item size , => size occuped in memory
a2.itemsize

8

In [22]:
# dtype 
print(a1.dtype)
print(a2.dtype)

int32
float64


CHANGING DATATYPE

In [27]:
# astype  => memeory optimisation ka tarika hai
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

Array Operation

In [30]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [31]:
# scalaar operations 

# aritmantic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [34]:
# realtional > , < , >= ,<= , ==

a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [36]:
# Vector Operations

# aritmetic

a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

Array Functions

In [46]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100,3)

a1

array([[36.717, 53.921,  4.767],
       [40.735, 56.149, 37.818],
       [88.331, 27.61 , 53.31 ]])

In [48]:
# max/min/sum/prod

np.max(a1)

np.sum(a1)

399.358

In [51]:
# max/min/sum/prod  => row wise

# 0=> col , 1 => row

np.max(a1, axis=1)

array([53.921, 56.149, 88.331])

In [55]:
# mean , median , std , var

np.median(a1, axis= 0)

array([40.735, 53.921, 37.818])

In [57]:
# trignometric functions -> not using
np.sin(a1)

array([[-0.83167186, -0.4915989 , -0.99850919],
       [ 0.10550776, -0.38911231,  0.11860829],
       [ 0.35826204,  0.61653482,  0.09692272]])

In [61]:
# dot product , (3, 4 ),(4, 3) , 4=4 , then only dot product

a1 = np.arange(0,12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)


np.dot(a1,a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [63]:
# log and exponants
np.log(a1)

np.exp(a1)

C:\Users\satya\AppData\Local\Temp\ipykernel_30004\2541496232.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [64]:
# round , floor , ceil

np.round(np.random.random((2,3))*100)

array([[40., 29., 90.],
       [45., 33., 15.]])

Indexing and Slicing

In [66]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [67]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
a1[-1]

9

In [69]:
a1[0]

0

In [71]:
# 2d array
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
a2[1,2]

6

In [73]:
a2[1,0]

4

In [74]:
# 3d d
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [75]:
# 5

a3[1, 0, 1 ]

5

In [76]:
# 0
a3 [0, 0 ,0]

0

In [77]:
# slicing

In [78]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
a1[2:5:2]

array([2, 4])

In [84]:
# matrix

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
a2[0]

array([0, 1, 2, 3])

In [86]:
a2[0,0:]

array([0, 1, 2, 3])

In [88]:
a2[:,2]

array([ 2,  6, 10])

In [91]:
# 5,6  9,10

a2[1:, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [93]:
# 0 3  8 11

a2[::2, ::3 ]

# :2 , jump

array([[ 0,  3],
       [ 8, 11]])

In [100]:
# 1 3 9 11
a2[::2 , 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [102]:
# 4 7
a2[1, ::3]

array([4, 7])

In [104]:
# 1 2 3   5 6 7

a2[0:2 , 1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [111]:
# tensor

a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [112]:
# 0 2   18 20  

a3[::2, 0, ::2]

array([[ 0,  2],
       [18, 20]])

Iterating

In [113]:
a1 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [115]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [117]:
for i in a1:
    print(i , end =" ")

0 1 2 3 4 5 6 7 8 9 

In [119]:
for i in a2:
    print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [121]:
for i in np.nditer(a3):
    print(i)

# a3 => ko 1 D mai convert kiya , aur print kar diya hai

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


RESHAPING

In [ ]:
# reshape

In [122]:
# Transpose

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [125]:
np.transpose(a2)

# or

a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [126]:
# ravel => any dimension  to 1D

a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Stacking

In [127]:
# horizontal stackup

a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [130]:
np.hstack((a4, a5 , a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [133]:
# vertical stacking

np.vstack((a4 , a5))

# shape should be same

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting

In [135]:
# hprizontal splitting  (  | ) , ooposite of stack
a6 = np.hstack((a4, a5 , a4))



In [136]:
np.hsplit(a6, 3)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])]