In [3]:
# Numpy

# kay hai aur iski jarurat kay hai ??

# Library used for scientific calculating.
# most important numpy array

# aawashakta : at initially , most of ml or ds are performed using matlab , or R , beacuse python is a slow programing language , 

# as list , dict etc , are vey slow 
# to overcome these => NUMPY , written in C , wrapped in python


In [4]:
# difference NDARRAY vs PYTHON sequences

# size is fixed
# same datatypes
# very convinenet
# famous library uses numpy

CREATING NUMPY ARRAYS

In [6]:
# import

import numpy as np 

# vector
a = np.array([1,2,3,4,5,6])
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [10]:
# matrix
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
# tensor
b = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(b)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [13]:
# different datatypes

np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [16]:
# np.arange  => same as range

np.arange(1,11)

np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [23]:
# np.reshape

np.arange(1,13).reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [25]:
# np.ones  and np.zeros

np.ones((3,4)) # => every item is 1

# to initalise the array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
# np.random

np.random.random((3,4))

array([[0.8947821 , 0.36094027, 0.89497883, 0.76840704],
       [0.32238008, 0.37018125, 0.36610553, 0.78162554],
       [0.67307856, 0.09115771, 0.01871715, 0.92163197]])

In [31]:
# np.linspace

np.linspace(-10, 10,10)
# lower range , upper range , total number of numbers

# it creates a linearly seprable points , difference between 2 linear points in same

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [32]:
# np.identity -> identity matrix

np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])