### Numpy Arrays vs Python Lists

In [2]:
# speed
# list

a = [i for i in range(10000000)]
b = [i for i in range(10000000, 20000000)]

c = []
import time

start = time.time()

for i in range (10000000):
    c.append(a[i] + b[i])

print(time.time() - start)

# dynamic array , referential array , stores according to address

2.010026693344116


In [3]:
# numpy  => uses c type of array, non dynamic 
import numpy as np

a = np.arange(10000000)
b = np.arange(10000000, 20000000)

start = time.time()
c = a + b
print(time.time() - start)

0.12358283996582031


In [4]:
# memory and convinent

a = [i for i in range(10000000)]

import sys

sys.getsizeof(a)

89095160

In [5]:
a = np.arange(10000000 , dtype= np.int32)
sys.getsizeof(a)

40000112

### Advance Indexing

In [6]:
# noumal indexig and slicing

a = np.arange(12).reshape(3,4)

a 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
# print 5 

print(a[1, 1])

5


In [13]:
# 2,3 6,7

print(a[0:2,2:4])

[[2 3]
 [6 7]]


In [19]:
# fancy indexing 

a = a.reshape(4,3)
a

# if no pattern fomrmred

a[[0,2,3]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
b = np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [23]:
# 1, 3 ,4 ,6 row

arr = [1,2,3,5]
arr

[1, 2, 3, 5]

In [26]:
# need 2nd and 4th column
b[:,[1,3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19],
       [21, 23]])

In [28]:
# * Boolean indexing =>  based on logic we need to remove the data , like numbers divisible by 5 , greater than 


# best way to filter data on basis of comditions


In [31]:
a = np.random.randint(1,100, 24).reshape(6,4)
a

array([[92, 96, 27, 49],
       [35, 88, 43, 57],
       [22, 80, 38, 67],
       [69, 29, 64, 59],
       [34, 98,  5,  5],
       [23, 15, 14, 22]])

In [34]:
# find greater than 50

print(a > 50)
# the output is an boolean array

# boolean masking now we will , put this output on a , and were is true it will print elese it will no print

a[a>50]

[[ True  True False False]
 [False  True False  True]
 [False  True False  True]
 [ True False  True  True]
 [False  True False False]
 [False False False False]]


array([92, 96, 88, 57, 80, 67, 69, 64, 59, 98])

In [37]:
# find out even numbers

a % 2 == 0

a[a % 2 == 0]

array([92, 96, 88, 22, 80, 38, 64, 34, 98, 14, 22])

In [43]:
# graeter than 50 , and even

(a > 50) & (a % 2 == 0)

a[(a > 50) & (a % 2 == 0)]

array([92, 96, 88, 80, 64, 98])

In [42]:
# numbers not divisibel by 7

a[~(a % 7 == 0)]

array([92, 96, 27, 88, 43, 57, 22, 80, 38, 67, 69, 29, 64, 59, 34,  5,  5,
       23, 15, 22])