### Broadcast

In [3]:
# We work with array of different sizes, we see how smaller array work during the arithmatic operation  

In [4]:
import numpy as np
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)


print(a)
print(b)

a+b


[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 6,  8, 10],
       [12, 14, 16]])

In [5]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,9)


print(a)
print(b)

a+b

[[0 1 2]
 [3 4 5]]
[6 7 8]


array([[ 6,  8, 10],
       [ 9, 11, 13]])

In [6]:
# Rules 

# 1)make arrays of same dimension , add 1 to the head , and see 

# example : [3,3]  and  [3]  , [3,3] and [1,3]  🟢

# example : [3,3]  and  [2] , [3,3] and [1,2]  🔴 


# 2) Make each dimension of the 2 arrays of same size

In [11]:
# examples

a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)

print(a+b)




[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [12]:
# (3,4) and (3) , error

a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a+b)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [16]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)

print()

print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [19]:
a = np.arange(4).reshape(2,2)
b = np.arange(1).reshape(1)

print(a)
print(b)

print()

print(a+b)



[[0 1]
 [2 3]]
[0]

[[0 1]
 [2 3]]


In [20]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)

print()

print(a+b)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]



ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [21]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)

# dimensions are same no changes 
print(a)
print(b)

print()

print(a+b)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]



ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

In [23]:
# rules again 

# 1) making same dimensions
# 2) expand 1 , until it matches

# uses , used in vectorisation , while dealing with huge amount of data 

# we dont use vectorisation , bo numpy karwata hai